openapi: "3.0.2"
info:
  title: Admin
  description: Endpoint for Seatlect admin management platform
  version: "1.0"
servers:
  - url: http://localhost:{port}/api/v1
    description: Local server
    variables:
      port:
        default: "9000"
paths:
  /admin/login:
    post:
      description: Login admin with given username and password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "204":
          description: Authentication was successful
        "401":
          description: Authentication failed with given credentials
        "500":
          description: Unknown error occurred
  /admin/business:
    get:
      description: Get list of businesses by status and page number
      parameters:
        - in: query
          name: status
          required: true
          schema:
            type: integer
        - in: query
          name: page
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Retrieved list of Businesses successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListBusinessResponse"

components:
  schemas:
    Business:
      type: object
      properties:
        businessName:
          type: string
        status:
          type: integer
        type:
          type: string
        tags:
          type: array
          items:
            type: string
        description:
          type: string
        location:
          type: object
          properties:
            latitude:
              type: string
            longitude:
              type: string
        address:
          type: string
        displayImage:
          type: string
        images:
          type: array
          items:
            type: string
        policy:
          type: object
          properties:
            minAge:
              type: integer
    LoginRequest:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
      required:
        - "username"
        - "password"
    ListBusinessResponse:
      type: object
      properties:
        businesses:
          type: array
          items:
            $ref: "#/components/schemas/Business"
