openapi: "3.0.2"
info:
  title: Admin
  description: Endpoint for Seatlect admin management platform
  version: "1.0"
servers:
  - url: http://localhost:{port}/api/v1
    description: Local server
    variables:
      port:
        default: "9000"
paths:
  /test:
    get:
      responses:
        "200":
          description: Test endpoint
