openapi: "3.0.2"
info:
  title: Business
  version: "1.0.0"
servers:
  - url: http://localhost:{port}/api/v1
    description: Local server
    variables:
      port:
        default: "9000"
paths:
  /business/{businessId}:
    get:
      description: Get Business information by ID
      parameters:
        - in: path
          name: businessId
          required: true
          schema:
            type: string
          description: ID of the Business
      responses:
        "200":
          description: Business information retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Business"
    patch:
      description: Update Business information by ID
      parameters:
        - in: path
          name: businessId
          required: true
          schema:
            type: string
            description: ID of the Business
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateBusinessResponse"
      responses:
        "200":
          description: Business information updated successfully
  /business/{businessId}/displayImage:
    put:
      description: Update Business displayImage by ID
      parameters:
        - in: path
          name: businessId
          required: true
          schema:
            type: string
            description: ID of the Business
      requestBody:
        content:
          image/png:
            schema:
              $ref: "#/components/schemas/ImageUpload"
      responses:
        "200":
          description: Display image updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UpdateDisplayImageResponse"
  /business/{businessId}/image:
    post:
      description: Append a new image to Business images
      parameters:
        - in: path
          name: businessId
          required: true
          schema:
            type: string
            description: ID of the Business
      requestBody:
        content:
          image/png:
            schema:
              $ref: "#/components/schemas/ImageUpload"
      responses:
        "200":
          description: Image appended
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AppendImageResponse"

components:
  schemas:
    Business:
      type: object
      properties:
        businessName:
          type: string
        type:
          type: string
        tags:
          type: array
          items:
            type: string
        description:
          type: string
        location:
          type: object
          properties:
            latitude:
              type: string
            longitude:
              type: string
        address:
          type: string
        displayImage:
          type: string
        images:
          type: array
          items:
            type: string
        policy:
          type: object
          properties:
            minAge:
              type: integer
    ImageUpload:
      type: string
      format: Binary
    UpdateBusinessResponse:
      type: object
      properties:
        businessName:
          type: string
        type:
          type: string
        tags:
          type: array
          items:
            type: string
        description:
          type: string
        location:
          type: object
          properties:
            latitude:
              type: string
            longitude:
              type: string
        address:
          type: string
        policy:
          type: object
          properties:
            minAge:
              type: integer
    UpdateDisplayImageResponse:
      type: object
      properties:
        displayImage:
          type: string
    AppendImageResponse:
      type: object
      properties:
        image:
          type: string
